# Generated by Django 5.2.4 on 2025-07-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tufshopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
